# GitHub Actions pipeline for DFA PDF microservice component
name: cd-dfa-pdf-service

on:
  push:
    branches:
      - support-develop
      - develop
    paths:
      - "pdf-service/**"
      - ".github/workflows/cd-dfa-pdf-service.yml"
  
  workflow_dispatch:

env:
  IMAGE_NAME: dfa-portal-pdf-service
  WORKING_DIRECTORY: ./pdf-service
  IMAGE_TAG: dev

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v3

      - name: Log into registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.DOCKER_SUPPORT_REGISTRY }}
          username: ${{ secrets.DOCKER_SUPPORT_USERNAME }}
          password: ${{ secrets.DOCKER_SUPPORT_BUILDER }}

      # Get SHORT_SHA to tag images
      - name: Get short SHA
        id: short_sha
        run: |
          echo "::set-output name=SHORT_SHA::$(git rev-parse --short HEAD)"
          echo "Short SHA: $SHORT_SHA"

      - name: Build Image
        working-directory: ${{env.WORKING_DIRECTORY}}
        run: |
          docker build -t ${{env.IMAGE_NAME}} .

      - name: Tag Image
        run: |
          docker tag ${{env.IMAGE_NAME}} ${{ secrets.DOCKER_SUPPORT_REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}

      - name: Docker Push
        run: |
          docker push ${{ secrets.DOCKER_SUPPORT_REGISTRY }}/${{env.IMAGE_NAME}}:${{ env.IMAGE_TAG }}
